[Weather]
acceleration = 0
acceleration.earliest_time = -30d
acceleration.cron_schedule = 5 * * * *
acceleration.manual_rebuilds = 1
dataset.type = datamodel
description = ZENTRA Cloud 15-minute measurement readings (long format: measurement, value, datetime)
