[zentra_weather_index]
definition = (index=weather OR index=main)
iseval = 0

[zentra_weather_search]
definition = `zentra_weather_index` (sourcetype=zentra:weather OR sourcetype=zentra_weather)
iseval = 0

[zentra_weather_datamodel]
definition = Weather
iseval = 0
