[zentra_weather_index]
definition = index=zentra_validate
iseval = 0

[zentra_weather_search]
definition = `zentra_weather_index` sourcetype=zentra:reading
iseval = 0

[zentra_interval_precip]
definition = `zentra_weather_search` measurement_canonical=precipitation
iseval = 0

[zentra_weather_datamodel]
definition = Weather
iseval = 0
